import { copyFile, mkdir, readFile, readdir, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';

const projectRoot = process.cwd();
const sourceRoot = path.join(projectRoot, 'src');
const fontsourceRoot = path.join(projectRoot, 'node_modules', '@fontsource');
const notoRoot = path.join(fontsourceRoot, 'noto-serif-sc');
const outputDirectory = path.join(sourceRoot, 'assets', 'fonts', 'generated');
const outputCss = path.join(sourceRoot, 'styles', 'fonts.generated.css');

const textExtensions = new Set(['.astro', '.md', '.ts']);
const notoWeights = [400, 600];
const latinFaces = [
  ['lora', 'latin-400.css'],
  ['lora', 'latin-400-italic.css'],
  ['lora', 'latin-600.css'],
  ['source-sans-3', 'latin-400.css'],
  ['source-sans-3', 'latin-500.css'],
  ['source-sans-3', 'latin-600.css'],
];

async function collectText(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const chunks = [];

  for (const entry of entries) {
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      chunks.push(await collectText(fullPath));
      continue;
    }

    if (textExtensions.has(path.extname(entry.name)) && !entry.name.endsWith('.generated.css')) {
      chunks.push(await readFile(fullPath, 'utf8'));
    }
  }

  return chunks.join('\n');
}

function collectNonAsciiCodePoints(text) {
  const codePoints = new Set();
  for (const character of text) {
    const codePoint = character.codePointAt(0);
    if (codePoint && codePoint > 0x7f) codePoints.add(codePoint);
  }
  return codePoints;
}

function unicodeTokenToRange(token) {
  const value = token.trim().replace(/^U\+/i, '');
  if (value.includes('?')) {
    return [
      Number.parseInt(value.replaceAll('?', '0'), 16),
      Number.parseInt(value.replaceAll('?', 'f'), 16),
    ];
  }

  const [start, end = start] = value.split('-');
  return [Number.parseInt(start, 16), Number.parseInt(end, 16)];
}

function blockCoversCodePoint(block, codePoints) {
  const match = block.match(/unicode-range:\s*([^;]+);/i);
  if (!match?.[1]) return true;

  const ranges = match[1].split(',').map(unicodeTokenToRange);
  for (const codePoint of codePoints) {
    if (ranges.some(([start, end]) => codePoint >= start && codePoint <= end)) return true;
  }
  return false;
}

function normalizeFontBlock(block) {
  return block
    .replace(/,\s*url\([^)]*\.woff\)\s*format\(['"]woff['"]\)/gi, '')
    .replace(/font-display:\s*swap;/gi, 'font-display: block;')
    .replace(
      /url\(\.\/files\/([^)]*\.woff2)\)/gi,
      'url("../assets/fonts/generated/$1")',
    );
}

async function clearGeneratedFonts() {
  await mkdir(outputDirectory, { recursive: true });
  const entries = await readdir(outputDirectory, { withFileTypes: true });
  await Promise.all(
    entries
      .filter((entry) => entry.isFile() && entry.name.endsWith('.woff2'))
      .map((entry) => unlink(path.join(outputDirectory, entry.name))),
  );
}

async function copyBlockFont(block, packageRoot) {
  const woff2Match = block.match(/url\(\.\/files\/([^)]*\.woff2)\)/i);
  const fileName = woff2Match?.[1];
  if (!fileName) return undefined;

  await copyFile(
    path.join(packageRoot, 'files', fileName),
    path.join(outputDirectory, fileName),
  );
  return normalizeFontBlock(block);
}

async function prepareLatinFaces() {
  const outputBlocks = [];
  for (const [packageName, cssName] of latinFaces) {
    const packageRoot = path.join(fontsourceRoot, packageName);
    const sourceCss = await readFile(path.join(packageRoot, cssName), 'utf8');
    const blocks = sourceCss.match(/@font-face\s*\{[^}]*\}/g) ?? [];
    for (const block of blocks) {
      const prepared = await copyBlockFont(block, packageRoot);
      if (prepared) outputBlocks.push(prepared);
    }
  }
  return outputBlocks;
}

async function prepareNotoWeight(weight, codePoints) {
  const sourceCss = await readFile(path.join(notoRoot, `${weight}.css`), 'utf8');
  const blocks = sourceCss.match(/@font-face\s*\{[^}]*\}/g) ?? [];
  const selectedBlocks = blocks.filter((block) => blockCoversCodePoint(block, codePoints));
  const outputBlocks = [];

  for (const block of selectedBlocks) {
    const prepared = await copyBlockFont(block, notoRoot);
    if (prepared) outputBlocks.push(prepared);
  }
  return outputBlocks;
}

const projectText = await collectText(sourceRoot);
const codePoints = collectNonAsciiCodePoints(projectText);
await clearGeneratedFonts();

const cssBlocks = await prepareLatinFaces();
for (const weight of notoWeights) {
  cssBlocks.push(...(await prepareNotoWeight(weight, codePoints)));
}

const header = '/* Generated by scripts/prepare-fonts.mjs. Do not edit manually. */\n';
await writeFile(outputCss, `${header}${cssBlocks.join('\n\n')}\n`, 'utf8');

console.log(
  `Prepared ${latinFaces.length} Latin faces and ${cssBlocks.length - latinFaces.length} Noto Serif SC unicode-range chunks.`,
);
